// flow-typed signature: 0c66a966599635c2d237722164455624
// flow-typed version: <<STUB>>/express-list-routes_v^0.1.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-list-routes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-list-routes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'express-list-routes/index' {
  declare module.exports: $Exports<'express-list-routes'>;
}
declare module 'express-list-routes/index.js' {
  declare module.exports: $Exports<'express-list-routes'>;
}
