// flow-typed signature: 860f2aa9b201179caa316ae72e9a29b5
// flow-typed version: <<STUB>>/git-http-backend_v^1.0.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-http-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-http-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-http-backend/example/band' {
  declare module.exports: any;
}

declare module 'git-http-backend/example/server' {
  declare module.exports: any;
}

declare module 'git-http-backend/lib/service' {
  declare module.exports: any;
}

declare module 'git-http-backend/test/test-server' {
  declare module.exports: any;
}

declare module 'git-http-backend/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-http-backend/example/band.js' {
  declare module.exports: $Exports<'git-http-backend/example/band'>;
}
declare module 'git-http-backend/example/server.js' {
  declare module.exports: $Exports<'git-http-backend/example/server'>;
}
declare module 'git-http-backend/index' {
  declare module.exports: $Exports<'git-http-backend'>;
}
declare module 'git-http-backend/index.js' {
  declare module.exports: $Exports<'git-http-backend'>;
}
declare module 'git-http-backend/lib/service.js' {
  declare module.exports: $Exports<'git-http-backend/lib/service'>;
}
declare module 'git-http-backend/test/test-server.js' {
  declare module.exports: $Exports<'git-http-backend/test/test-server'>;
}
declare module 'git-http-backend/test/test.js' {
  declare module.exports: $Exports<'git-http-backend/test/test'>;
}
