// flow-typed signature: e0b9d3ec5597a4e6b4ee3196268ab8aa
// flow-typed version: <<STUB>>/promise.prototype.finally_v^3.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise.prototype.finally'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise.prototype.finally' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise.prototype.finally/auto' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/implementation' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/polyfill' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/requirePromise' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/shim' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/test/builtin' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/test/index' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/test/native' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/test/promise-shimmed' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/test/shimmed' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/test/test262-prelude' {
  declare module.exports: any;
}

declare module 'promise.prototype.finally/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise.prototype.finally/auto.js' {
  declare module.exports: $Exports<'promise.prototype.finally/auto'>;
}
declare module 'promise.prototype.finally/implementation.js' {
  declare module.exports: $Exports<'promise.prototype.finally/implementation'>;
}
declare module 'promise.prototype.finally/index' {
  declare module.exports: $Exports<'promise.prototype.finally'>;
}
declare module 'promise.prototype.finally/index.js' {
  declare module.exports: $Exports<'promise.prototype.finally'>;
}
declare module 'promise.prototype.finally/polyfill.js' {
  declare module.exports: $Exports<'promise.prototype.finally/polyfill'>;
}
declare module 'promise.prototype.finally/requirePromise.js' {
  declare module.exports: $Exports<'promise.prototype.finally/requirePromise'>;
}
declare module 'promise.prototype.finally/shim.js' {
  declare module.exports: $Exports<'promise.prototype.finally/shim'>;
}
declare module 'promise.prototype.finally/test/builtin.js' {
  declare module.exports: $Exports<'promise.prototype.finally/test/builtin'>;
}
declare module 'promise.prototype.finally/test/index.js' {
  declare module.exports: $Exports<'promise.prototype.finally/test/index'>;
}
declare module 'promise.prototype.finally/test/native.js' {
  declare module.exports: $Exports<'promise.prototype.finally/test/native'>;
}
declare module 'promise.prototype.finally/test/promise-shimmed.js' {
  declare module.exports: $Exports<'promise.prototype.finally/test/promise-shimmed'>;
}
declare module 'promise.prototype.finally/test/shimmed.js' {
  declare module.exports: $Exports<'promise.prototype.finally/test/shimmed'>;
}
declare module 'promise.prototype.finally/test/test262-prelude.js' {
  declare module.exports: $Exports<'promise.prototype.finally/test/test262-prelude'>;
}
declare module 'promise.prototype.finally/test/tests.js' {
  declare module.exports: $Exports<'promise.prototype.finally/test/tests'>;
}
