// flow-typed signature: 614be88c5fe5c81059f55dbecfb69e67
// flow-typed version: <<STUB>>/tap-diff_v^0.1.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tap-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tap-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tap-diff/distributions/cli' {
  declare module.exports: any;
}

declare module 'tap-diff/distributions/index' {
  declare module.exports: any;
}

declare module 'tap-diff/sources/cli' {
  declare module.exports: any;
}

declare module 'tap-diff/sources/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tap-diff/distributions/cli.js' {
  declare module.exports: $Exports<'tap-diff/distributions/cli'>;
}
declare module 'tap-diff/distributions/index.js' {
  declare module.exports: $Exports<'tap-diff/distributions/index'>;
}
declare module 'tap-diff/sources/cli.js' {
  declare module.exports: $Exports<'tap-diff/sources/cli'>;
}
declare module 'tap-diff/sources/index.js' {
  declare module.exports: $Exports<'tap-diff/sources/index'>;
}
