// flow-typed signature: d77d2c2d7a3f7dbe95e14f36b31ad7b9
// flow-typed version: <<STUB>>/tape-watch2_v^0.1.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tape-watch2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tape-watch2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tape-watch2/test/fixture/a' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/fixture/b' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/fixture/c-1' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/fixture/c-2-1' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/fixture/c-2' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/fixture/c' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/fixture/test/test-b' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/fixture/test/test-c-1' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/fixture/test/test-c-2-1' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/fixture/test/test-c-2' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/fixture/test/test-c' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/test-cli' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/test-functions' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/test-hook' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/test-watch' {
  declare module.exports: any;
}

declare module 'tape-watch2/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tape-watch2/index' {
  declare module.exports: $Exports<'tape-watch2'>;
}
declare module 'tape-watch2/index.js' {
  declare module.exports: $Exports<'tape-watch2'>;
}
declare module 'tape-watch2/test/fixture/a.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/a'>;
}
declare module 'tape-watch2/test/fixture/b.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/b'>;
}
declare module 'tape-watch2/test/fixture/c-1.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/c-1'>;
}
declare module 'tape-watch2/test/fixture/c-2-1.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/c-2-1'>;
}
declare module 'tape-watch2/test/fixture/c-2.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/c-2'>;
}
declare module 'tape-watch2/test/fixture/c.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/c'>;
}
declare module 'tape-watch2/test/fixture/test/test-b.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/test/test-b'>;
}
declare module 'tape-watch2/test/fixture/test/test-c-1.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/test/test-c-1'>;
}
declare module 'tape-watch2/test/fixture/test/test-c-2-1.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/test/test-c-2-1'>;
}
declare module 'tape-watch2/test/fixture/test/test-c-2.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/test/test-c-2'>;
}
declare module 'tape-watch2/test/fixture/test/test-c.js' {
  declare module.exports: $Exports<'tape-watch2/test/fixture/test/test-c'>;
}
declare module 'tape-watch2/test/test-cli.js' {
  declare module.exports: $Exports<'tape-watch2/test/test-cli'>;
}
declare module 'tape-watch2/test/test-functions.js' {
  declare module.exports: $Exports<'tape-watch2/test/test-functions'>;
}
declare module 'tape-watch2/test/test-hook.js' {
  declare module.exports: $Exports<'tape-watch2/test/test-hook'>;
}
declare module 'tape-watch2/test/test-watch.js' {
  declare module.exports: $Exports<'tape-watch2/test/test-watch'>;
}
declare module 'tape-watch2/test/utils.js' {
  declare module.exports: $Exports<'tape-watch2/test/utils'>;
}
