// flow-typed signature: 7ddb1585553f156651b0a866fc7bdf42
// flow-typed version: <<STUB>>/time-elements_v^1.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'time-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'time-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'time-elements/dist/time-elements-legacy' {
  declare module.exports: any;
}

declare module 'time-elements/dist/time-elements' {
  declare module.exports: any;
}

declare module 'time-elements/prettier.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'time-elements/dist/time-elements-legacy.js' {
  declare module.exports: $Exports<'time-elements/dist/time-elements-legacy'>;
}
declare module 'time-elements/dist/time-elements.js' {
  declare module.exports: $Exports<'time-elements/dist/time-elements'>;
}
declare module 'time-elements/prettier.config.js' {
  declare module.exports: $Exports<'time-elements/prettier.config'>;
}
